//
//  LocaText.swift
//  ICE VPN
//
//  Created by tgg on 2023/6/1.
//

import Foundation

/// mine
let LocalMineNode = "LocalMineNode"
let LocalMineLanguage = "LocalMineLanguage"
let LocalMineTerms = "LocalMineTerms"
let LocalMinePrivacy = "LocalMinePrivacy"
let LocalMineHelp = "LocalMineHelp"
let LocalMineVersion = "LocalMineVersion"
let LocalMineLogout = "LocalMineLogout"
let LocalMineLogoff = "LocalMineLogoff"
let LocalProfileTitle = "LocalProfileTitle"
let LocalProfileName = "LocalProfileName"
let LocalProfilePwd = "LocalProfilePwd"
let LocalNickName = "LocalNickName"
let LocalProfileOldPwd = "LocalProfileOldPwd"
let LocalProfileNewPwd = "LocalProfileNewPwd"
let LocalBindReward = "LocalBindReward"
let LocalRewardTitle = "LocalRewardTitle"
let LocalRewardDesc = "LocalRewardDesc"
let LocalInvitationCode = "LocalInvitationCode"
let LocalInvitationTotal = "LocalInvitationTotal"
let LocalInvitationPaid = "LocalInvitationPaid"
let LocalInvitationFree = "LocalInvitationFree"
let LocalDurationDay = "LocalDurationDay"
let LocalGetCommission = "LocalGetCommission"
let LocalTokenReward = "LocalTokenReward"
let LocalMyInvitation = "LocalMyInvitation"
let LocalCopyCode = "LocalCopyCode"
let LocalQRShare = "LocalQRShare"
let LocalBindTitle = "LocalBindTitle"
let LocalBindButton = "LocalBindButton"
let LocalShareTitle1 = "LocalShareTitle1"
let LocalShareTitle2 = "LocalShareTitle2"
let LocalShareDesc = "LocalShareDesc"
let LocalShareScan = "LocalShareScan"
let LocalRebateAddress = "LocalRebateAddress"

/// vpn
let LocalVPNTitle = "LocalVPNTitle"
let LocalVPNProtocol = "LocalVPNProtocol"
let LocalSwitchLeft = "LocalSwitchLeft"
let LocalSwitchRight = "LocalSwitchRight"
let LocalConnectButton = "LocalConnectButton"
let LocalDisconnectButton = "LocalDisconnectButton"
let LocalEndPointTitle = "LocalEndPointTitle"
let LocalPayingSection = "LocalPayingSection"
let LocalFreeSection = "LocalFreeSection"
let LocalVipButton = "LocalVipButton"
let LocalVPNProtect = "LocalVPNProtect"
let LocalVPNProtected = "LocalVPNProtected"
let LocalVPNPosition = "LocalVPNPosition"
let LocalVPNIP = "LocalVPNIP"
let LocalIPReal = "LocalIPReal"
let LocalIPHide = "LocalIPHide"
let LocalIPTip = "LocalIPTip"
let LocalIPPresent = "LocalIPPresent"
let LocalConnectionTime = "LocalConnectionTime"
let LocalConnectionTitle = "LocalConnectionTitle"
let LocalNodeTitle1 = "LocalNodeTitle1"
let LocalNodeTitle2 = "LocalNodeTitle2"
let LocalNodeDetail1 = "LocalNodeDetail1"
let LocalNodeDetail2 = "LocalNodeDetail2"
let LocalNodeDetail3 = "LocalNodeDetail3"
let LocalNodeDetail4 = "LocalNodeDetail4"
let LocalNodeKnownButton = "LocalNodeKnownButton"
let LocalUpgradedTitle = "LocalUpgradedTitle"
let LocalUpgradedDesc = "LocalUpgradedDesc"
let LocalUpgradeTitle = "LocalUpgradeTitle"
let LocalUpgradeDesc1 = "LocalUpgradeDesc1"
let LocalUpgradeDesc2 = "LocalUpgradeDesc1"
let LocalUpgradeTip1 = "LocalUpgradeTip1"
let LocalUpgradeTip1Desc = "LocalUpgradeTip1Desc"
let LocalUpgradeTip2 = "LocalUpgradeTip2"
let LocalUpgradeTip2Desc = "LocalUpgradeTip2Desc"
let LocalUpgradeTip3 = "LocalUpgradeTip3"
let LocalUpgradeTip3Desc = "LocalUpgradeTip3Desc"
let LocalFreeTimeMin = "LocalFreeTimeMin"
let LocalFreeTimeDay = "LocalFreeTimeDay"
let LocalNOFreeTime = "LocalNOFreeTime"
let LocalAINode = "ai"
let LocalCountrySG = "SG"
let LocalCountryHK = "HK"
let LocalCountryUS = "US"
let LocalCountryAU = "AU"
let LocalCountryMY = "MY"
let LocalCountryIN = "IN"
let LocalCountryJP = "JP"
let LocalCountryUK = "UK"

/// login
let LocalLoginTitle = "LocalLoginTitle"
let LocalLoginTitleDesc = "LocalLoginTitleDesc"
let LocalLoginEmail = "LocalLoginEmail"
let LocalLoginEmailDesc = "LocalLoginEmailDesc"
let LocalLoginPassword = "LocalLoginPassword"
let LocalLoginPasswordDesc = "LocalLoginPasswordDesc"
let LocalLoginButton = "LocalLoginButton"
let LocalForgetButton = "LocalForgetButton"
let LocalRegisterDesc = "LocalRegisterDesc"
let LocalRegisterTitleDesc = "LocalRegisterTitleDesc"
let LocalRegisterPasswordDesc = "LocalRegisterPasswordDesc"
let LocalRegisterReferrer = "LocalRegisterReferrer"
let LocalRegisterReferrerDesc = "LocalRegisterReferrerDesc"
let LocalRegisterButton = "LocalRegisterButton"
let LocalLoginDesc = "LocalLoginDesc"
let LocalForgetPasswordTitle = "LocalForgetPasswordTitle"
let LocalNextButton = "LocalNextButton"
let LocalOTPTitle = "LocalOTPTitle"
let LocalOTPTitleDesc = "LocalOTPTitleDesc"
let LocalOTPTip = "LocalOTPTip"
let LocalOTPResend = "LocalOTPResend"
let LocalResetTitleDesc = "LocalResetTitleDesc"
let LocalNewPassword = "LocalNewPassword"
let LocalConfirmPassword = "LocalConfirmPassword"
let LocalSaveButton = "LocalSaveButton"

/// wallet
let LocalSearchOrInputWebAddress = "LocaSearchOrInputWebAddress"
let LocalNotData = "LocaNotData"
let LocalDappRiskSure = "LocalDappRiskSure"
let LocalDetail = "LocalDetail"
let LocalRequestDappTitle = "LocalRequestDappTitle"
let LocalDappRiskContent1 = "LocalDappRiskContent1"
let LocalDappRiskContent2 = "LocalDappRiskContent2"
let LocalCancle = "LocalCancle"
let LocalConfirm = "LocalConfirm"
let LocalRecently = "LocalRecently"
let LocalRecommended = "LocalRecommended"
let LocalHistoryRecord = "LocalHistoryRecord"
let LocalPayPassword = "LocalPayPassword"
let LocalSendAddress = "LocalSendAddress"
let LocalReviceAddress = "LocalReviceAddress"
let LocalInputMnemonicAndSpace = "LocalInputMnemonicAndSpace"
let LocalCurrentPassword = "LocalCurrentPassword"
let LocalWalletPasswordFormatError = "LocalWalletPasswordFormatError"
let LocalPasswordError = "LocalPasswordError"
let LocalDifferentPassword = "LocalDifferentPassword"
let LocalPasswordUpdateSuccess = "LocalPasswordUpdateSuccess"
let LocalMenmonicValidationFail = "LocalMenmonicValidationFail"
let LocalWallet = "LocalWallet"
let LocalWalletPasswprd = "LocalWalletPasswprd"
let LocalCreateWallet = "LocalCreateWallet"
let LocalImportWallet = "LocalImportWallet"
let LocalTransferSuccess = "LocalTransferSuccess"
let LocalCreate = "LocalCreate"
let LocalSetWalletName = "LocalSetWalletName"
let LocalOutPutPrompt = "LocalOutPutPrompt"
let LocalCopyAddress = "LocalCopyAddress"
let LocalCreateTips = "LocalCreateTips"
let LocalPleaseWalletName = "LocalPleaseWalletName"
let LocalBackupMnemonic = "LocalBackupMnemonic"
let LocalBackupMnemonicTips1 = "LocalBackupMnemonicTips1"
let LocalBackupMnemonicTips2 = "LocalBackupMnemonicTips2"
let LocalReceive = "LocalReceive"
let LocalScanReceive = "LocalScanReceive"
let LocalSendTo = "LocalSendTo"
let LocalAmount = "LocalAmount"
let LocalAll = "LocalAll"
let LocalReceiveAddress = "LocalReceiveAddress"
let LocalInputReceiveAddress = "LocalInputReceiveAddress"
let LocalDidNotGetFee = "LocalDidNotGetFee"
let LocalWalletName = "LocalWalletName"
let LocalMnemonicOrPrivateKey = "LocalMnemonicOrPrivateKey"
let LocalMnemonicError = "LocalMnemonicError"
let LocalMnemonicOrPrivateKeyError = "LocalMnemonicOrPrivateKeyError"
let LocalWalletAddress = "LocalWalletAddress"
let LocalExportPrivateKey = "LocalExportPrivateKey"
let LocalUpdatePassword = "LocalUpdatePassword"
let LocalForgetPassword = "LocalForgetPassword"
let LocalExportMnemonic = "LocalExportMnemonic"
let LocalExportPrivateKeyTips = "LocalExportPrivateKeyTips"
let LocalCopy = "LocalCopy"
let LocalManage = "LocalManage"
let LocaConfimPassword = "LocaConfimPassword"
let LocalExitWallet = "LocalExitWallet"
let LocalBindTips = "LocalBindTips"
let LocalMainNetwork = "LocalMainNetwork"
let LocalBackupVerification = "LocalBackupVerification"
let LocalWalletBindOtherAccount = "LocalWalletBindOtherAccount"
/// http
let LocalHttpDownloadError = "LocalHttpDownloadError"

/// alert
let LocalAlertLoginTitle = "LocalAlertLoginTitle"
let LocalAlertContinue = "LocalAlertContinue"
let LocalAlertCancel = "LocalAlertCancel"
let LocalAlertRegisterTitle = "LocalAlertRegisterTitle"
let LocalAlertResetPwdTitle = "LocalAlertResetPwdTitle"
let LocalAlertLogoutTitle = "LocalAlertLogoutTitle"
let LocalAlertLogoffTitle = "LocalAlertLogoffTitle"
let LocalAlertSetNameTitle = "LocalAlertSetNameTitle"
let LocalAlertSetPwdTitle = "LocalAlertSetPwdTitle"
let LocalAlertBindTitle = "LocalAlertBindTitle"

/// error
let LocalOTPError = "LocalOTPError"
let LocalOTPVerifyError = "LocalOTPVerifyError"
let LocalRegisterError = "LocalRegisterError"
let LocalLoginError = "LocalLoginError"
let LocalResetPwdError = "LocalResetPwdError"
let LocalLogoutError = "LocalLogoutError"
let LocalLogoffError = "LocalLogoffError"
let LocalSetNameError = "LocalSetNameError"
let LocalSetPwdError = "LocalSetNameError"
let LocalPayError = "LocalPayError"
let LocalBindError = "LocalBindError"

/// text
let LocalTermText = "LocalTermText"
let LocalPrivacyText = "LocalPrivacyText"
let LocalHelpQ1 = "LocalHelpQ1"
let LocalHelpQ2 = "LocalHelpQ2"
let LocalHelpQ3 = "LocalHelpQ3"
let LocalHelpQ4 = "LocalHelpQ4"
let LocalHelpQ5 = "LocalHelpQ5"
let LocalHelpQ6 = "LocalHelpQ6"
let LocalHelpQ7 = "LocalHelpQ7"
let LocalHelpQ8 = "LocalHelpQ8"
let LocalHelpQ9 = "LocalHelpQ9"
let LocalHelpQ10 = "LocalHelpQ10"
let LocalHelpQ11 = "LocalHelpQ11"
let LocalHelpQ12 = "LocalHelpQ12"
let LocalHelpQ13 = "LocalHelpQ13"
let LocalHelpQ14 = "LocalHelpQ14"
let LocalHelpA1 = "LocalHelpA1"
let LocalHelpA2 = "LocalHelpA2"
let LocalHelpA3 = "LocalHelpA3"
let LocalHelpA4 = "LocalHelpA4"
let LocalHelpA5 = "LocalHelpA5"
let LocalHelpA6 = "LocalHelpA6"
let LocalHelpA7 = "LocalHelpA7"
let LocalHelpA8 = "LocalHelpA8"
let LocalHelpA9 = "LocalHelpA9"
let LocalHelpA10 = "LocalHelpA10"
let LocalHelpA11 = "LocalHelpA11"
let LocalHelpA12 = "LocalHelpA12"
let LocalHelpA13 = "LocalHelpA13"
let LocalHelpA14 = "LocalHelpA14"

